#About: Script for parsing .json result files generated by iperf and getting the throughput, cwnd data
#!/usr/bin/env python3

import json
import sys
CC_ALGO = sys.argv[1]
START_RWND = int(sys.argv[2])
END_RWND = int(sys.argv[3])
RWND_INC_DEC = int(sys.argv[4])
TRIALS = int(sys.argv[5])
DURATION = 13

OUTPUT_FILE = '/home/harsh/data/json_files/summary_' + CC_ALGO + '.txt'
res_file = open(OUTPUT_FILE, "w")
res_file.close()
res_file = open(OUTPUT_FILE, "a+")

if(RWND_INC_DEC > 0):
    END_RWND = END_RWND + 1
else:
    END_RWND = END_RWND - 1

for rwnd in range(START_RWND, END_RWND, RWND_INC_DEC):
	total_bytes = 0
	total_sec = 0
	total_snd_cwnd = 0
	for trial in range(TRIALS):
		file = '/home/harsh/data/json_files/' + CC_ALGO + '_' + str(rwnd) + '_t' + str(trial) + '.json'
		f = open(file)
		data = json.load(f)
		for i in range(2,DURATION-1):
			total_bytes += data["intervals"][i]["sum"]["bytes"]
			total_sec += data["intervals"][i]["sum"]["seconds"]
			total_snd_cwnd += data["intervals"][i]["streams"][0]["snd_cwnd"]
	res_th_mbps = (total_bytes*8)/(total_sec*1000000)
	res_th_mbps = round(res_th_mbps, 2)
	res_snd_cwnd = total_snd_cwnd/30
	res_snd_cwnd = int(round(res_snd_cwnd, 0))
	res_file.write(str(rwnd*128/1000) + ' ' + str(res_th_mbps) + ' ' + str(res_snd_cwnd/1000) + '\n')
	
##################
# To be run on internetcc1 VM for getting summary for the json files generated by iperf
##################
